text changes for v1.0.0
bloxapp/ssv-scanner pull request #6
Opened 2023-06-11 09:20 UTC by vadiminc

2023-06-11 09:21 UTC, axelrod-blox approved these changes

2023-06-11 09:32 UTC, yoanatanblox commented on package.json
> +  "description": "Tool for retrieving events data (cluster snapshots and registration nonce) from the SSV network contract.",
“Tool for retrieving events data (cluster snapshots and owner nonce) from the SSV network contract.”

2023-06-11 09:42 UTC, yoanatanblox requested changes

2023-06-11 09:42 UTC, yoanatanblox commented on package.json
> +  "description": "Tool for retrieving events data (cluster snapshots and registration nonce) from the SSV network contract.",
“Tool for retrieving events data (cluster snapshots and owner nonce) from the SSV network contract.”

2023-06-12 09:48 UTC, andrew-blox approved these changes

2023-06-14 07:37 UTC, yoanatanblox commented on package.json
> +  "description": "Tool for retrieving events data (cluster snapshots and registration nonce) from the SSV network contract.",
registration nonce -> owner nonce

2023-06-14 08:59 UTC, meshin-dev approved these changes

2023-06-14 10:01 UTC, merged