Vc/multi abis
bloxapp/ssv-scanner pull request #7
Opened 2023-08-21 13:45 UTC by vadiminc

2023-08-29 07:29 UTC, meshin-dev requested changes
@vadiminc I had conversation with Jon regarding the new approach for scanner and liquidator args. Let's review what we going to do with that.

2023-08-29 08:18 UTC, axelrod-blox approved these changes

2023-10-12 07:29 UTC, meshin-dev approved these changes

2023-10-23 15:31 UTC, andrew-blox approved these changes

2023-10-25 10:49 UTC, merged